[package]
name = "rules"
version = "0.9.0"
authors = ["Elias Puma <elpumitaelias@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
